### ISSUE TITLE
Outdated Data Displaying

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/galter_dashing#37]
Something is up with the data being fed into dashing. 

- Image Slides are not displaying latest published
- News is not updating
- Classes are not updating

**Comment by Meowcenary** [comment]
We had our monthly call with FSMIT and brought up the issues we found after our investigation of the issue. Ostensibly the issue is a result of a problem with the library OpenSSL not having up to date certificate authorities (third party that verifies an ssl certificate) on the server. Austin has opened a ticket with FSMIT as they mentioned that there was an issue with certificate authorities sometime around May which is when this initially became an issue.

**Comment by sharpattack** [comment]
From Marc: 

> 
> One of the CA certificates in the SSL certificate chain expired in May 2020. Internet browsers have no problem with the expiration, since the browser can follow a secondary SSL chain automatically.
>  
> Command line tools (e.g. wget, curl, openssl, etc...), on the other hand, are having issues to verify the SSL server certificate, if the SSL chain is broken due to an expired CA certificate.

The SSL chains have been updated for the urls dashing was trying to call. This is fixed, and no changes were needed from us.
